services:
  api-pyservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-ppabe-python
    restart: always
    env_file:
      - .env
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    working_dir: /app
    # Llamamos a gunicorn directamente usando su binario absoluto en /usr/local/bin
    command: /usr/local/bin/gunicorn --bind 0.0.0.0:4001 index:app --workers 4 --timeout 120

networks:
  default:
    driver: bridge