version: "3.9"

services:
  api-pyservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppabe-pyservice:latest
    container_name: api-pyservice
    restart: unless-stopped

    env_file:
      - .env

    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app
      FLASK_ENV: production

    ports:
      - "4001:4001"

    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./logs:/app/src/utils/log

    command: ["gunicorn", "--bind", "0.0.0.0:4001", "index:app", "--workers", "2", "--timeout", "120"]

    networks:
      - backend_net

networks:
  backend_net:
