services:
  api-pyservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppabe-pyservice:latest
    container_name: api-ppabe-python
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app
      PORT: 4001
    ports:
      - "4001:4001"
    volumes:
      - .:/app:z
    working_dir: /app
    command: ["gunicorn", "--bind", "0.0.0.0:4001", "index:app", "--workers", "2", "--timeout", "120"]

networks:
  default:
    driver: bridge